version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecosure
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: sh -c "npx prisma db push && node src/index.js"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecosure?schema=public
      - JWT_SECRET=change-me
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FILE_STORAGE_LOCAL=true
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
